# Generated by Django 6.0.2 on 2026-08-05 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=6, unique=True)),
                ('marca', models.CharField(max_length=60)),
                ('modelo', models.CharField(max_length=60)),
                ('estado', models.CharField(choices=[('NUEVO', 'Nuevo'), ('USADO', 'Usado')], max_length=10)),
                ('color', models.CharField(max_length=40)),
                ('kilometraje', models.PositiveIntegerField()),
                ('descripcion', models.TextField(blank=True)),
                ('precio', models.PositiveBigIntegerField()),
                ('puntaje', models.FloatField(default=0.0)),
                ('publicado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('correo', models.EmailField(max_length=254)),
                ('direccion', models.CharField(max_length=200)),
                ('numero_tel', models.CharField(max_length=20)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoCarro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('SOAT', 'SOAT'), ('TECNOMECANICA', 'Revisión tecnomecánica'), ('TARJETA_PROPIEDAD', 'Tarjeta de propiedad')], max_length=20)),
                ('fecha_expedicion', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('archivo', models.FileField(blank=True, null=True, upload_to='documentos/')),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='marketplace.carro')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.PositiveBigIntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('metodo_pago', models.CharField(max_length=40)),
                ('estado', models.CharField(default='PENDIENTE', max_length=20)),
                ('carro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='marketplace.carro')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='marketplace.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Resena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('autor', models.CharField(max_length=120)),
                ('tipo', models.CharField(max_length=40)),
                ('carro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to='marketplace.carro')),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('correo', models.EmailField(max_length=254)),
                ('direccion', models.CharField(max_length=200)),
                ('numero_tel', models.CharField(max_length=20)),
                ('resena', models.PositiveIntegerField(default=0)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendedor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Repuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=80)),
                ('modelo_carro', models.CharField(max_length=80)),
                ('precio', models.PositiveBigIntegerField()),
                ('numero_serie', models.CharField(max_length=60, unique=True)),
                ('estado', models.CharField(choices=[('NUEVO', 'Nuevo'), ('USADO', 'Usado')], max_length=10)),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repuestos', to='marketplace.vendedor')),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_repuesto', models.PositiveIntegerField(default=0)),
                ('cantidad_carro', models.PositiveIntegerField(default=0)),
                ('vendedor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='marketplace.vendedor')),
            ],
        ),
        migrations.AddField(
            model_name='carro',
            name='vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carros', to='marketplace.vendedor'),
        ),
    ]
