# Generated by Django 6.0.2 on 2026-08-24 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CarritoCompra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad_producto", models.PositiveIntegerField(default=0)),
                ("precio_total", models.PositiveBigIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name="carro",
            name="carrito_compra",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="carros",
                to="marketplace.carritocompra",
            ),
        ),
        migrations.AddField(
            model_name="repuesto",
            name="carrito_compra",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="repuestos",
                to="marketplace.carritocompra",
            ),
        ),
    ]
