# Generated by Django 6.0.2 on 2026-08-25 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_carrito_compra'),
        ('marketplace', '0002_pagos'),
    ]

    operations = [
    ]
