"""
Django settings for carfit project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    'DJANGO_SECRET_KEY',
    'django-insecure-eo#e4p=(0dyrlzqzde+#ule^1^e7&9d6&j@dq_if160@3(z_t4',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_DEBUG', 'True') == 'True'

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'marketplace',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'carfit.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'marketplace.context_processors.carrito_compra',
            ],
        },
    },
]

WSGI_APPLICATION = 'carfit.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es-co'

TIME_ZONE = 'America/Bogota'

USE_I18N = True

USE_TZ = True

# Con es-co, formatea los enteros con puntos de miles al mostrarlos en las
# plantillas ($95.000.000 en vez de $95000000).
USE_THOUSAND_SEPARATOR = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Autenticación

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'marketplace:crear_articulo'
LOGOUT_REDIRECT_URL = '/'


# Django REST Framework: toda la API vive en marketplace/api/.
# Autenticación por cookie de sesión (la misma que usan las vistas HTML) y
# acceso denegado por defecto: cada vista habilita explícitamente el
# permiso que necesita (p. ej. LoginAPIView es la única AllowAny).

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}


# Correo. El notificador REAL usa este backend; el MOCK no lo toca.

EMAIL_BACKEND = os.getenv(
    'DJANGO_EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend'
)
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'no-responder@carfit.co')


# Django REST Framework.
#
# La autenticación por sesión sirve para probar la API desde el navegador con
# el mismo login del sitio; la básica, para hacerlo con curl o Postman sin
# montar tokens todavía. La API queda cerrada por defecto: cada vista pide
# explícitamente lo que necesita.

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
}


# Selección de implementaciones vía Factory (ver marketplace/infra/factories.py).
# Se leen con os.getenv dentro de las factories; se listan aquí como
# documentación del contrato de configuración:
#   VALIDADOR_DOCUMENTAL = MOCK | REAL   (default: MOCK)
#   NOTIFICADOR          = MOCK | REAL   (default: MOCK)
#   PASARELA_PAGO        = MOCK | REAL   (default: MOCK)
#   NOTIFICADOR_PAGOS    = MOCK | REAL   (default: MOCK)
#
# Con PASARELA_PAGO=REAL, el agregador necesita además:
#   PASARELA_URL         URL base de la API del agregador
#   PASARELA_LLAVE       llave privada de comercio
#   PASARELA_TIMEOUT     segundos de espera (default: 10)


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {'class': 'logging.StreamHandler'},
    },
    'loggers': {
        'marketplace': {'handlers': ['console'], 'level': 'INFO'},
    },
}
